### ISSUE TITLE
Parse real sizes (512M, 2G, ...) instead of just a number of GiB

### ISSUE THREAD

**Issue by markdryan** [intel/ccloudvm#10]
At the moment we can only specify the VM memory size as an int, the number of GiB to allocate. That's not ideal, the user should be able to specify any size.

**Comment by markdryan** [comment]
This will be important when we add support for multiple VMs.

**Comment by markdryan** [comment]
Original issue https://github.com/ciao-project/ciao/issues/1363

**Comment by rbradford** [comment]
Maybe we could use: https://godoc.org/github.com/alecthomas/units ?

**Comment by markdryan** [comment]
Great.  It looks perfect.
