### ISSUE TITLE
ccloudvm needs a way to copy folders from host into the guest VM

### ISSUE THREAD

**Issue by markdryan** [intel/ccloudvm#5]
Currently, the only way to share files between the host and the guest is to use 9p file sharing.  In some cases we don't actually need to share the files.  We just need to copy them into the guest.  Although this affect can be achieved via 9p, 9p doesn't always work correctly.  Therefore we need a fallback copy solution.  The main use case for this at the moment is to be able to run our bat tests inside semaphore-ci.

The copy could be done with ssh or we could simply include the files in the iso image we use to provision the VM.

**Comment by markdryan** [comment]
Original issue https://github.com/ciao-project/ciao/issues/1285

**Comment by ganeshmaharaj** [comment]
Currently i am able to get this working with `scp -i <key> -P 10022 ......`. The only problem with this being if i re-create the VM, i need to flush my known_hosts to get it going again. Are you thinking something that will circumvent this and do a 9p based copy support?

**Comment by markdryan** [comment]
@ganeshmaharaj You could try specifying the following options to scp

-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

These are the options used by the ccloudvm connect command.

I guess I was thinking that ccloudvm copy would just be essentially short hand for

scp -q -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i <key> 127.0.0.1 -p 10022

**Comment by ganeshmaharaj** [comment]
Ohh.. yes.  Definitely 😀
