### ISSUE TITLE
Xenial image no write on mounted drives

### ISSUE THREAD

**Issue by ganeshmaharaj** [intel/ccloudvm#50]
Just leaving it here so that others are aware of it. It seems there is an issue with libvirtd used in ubuntu releases that is causing the mounted drives to be readable but prevents us from writing to them. https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1559317

the bug doesn't show clearly the status of the bug or the release of libvirt that fixes it. But here are the info about my env.
Xenial 16.04
```
sudo apt-cache policy libvirt-bin
[sudo] password for ganeshma: 
libvirt-bin:
  Installed: 1.3.1-1ubuntu10.15
  Candidate: 1.3.1-1ubuntu10.15
```

**Comment by markdryan** [comment]
@ganeshmaharaj ccloudvm doesn't use libvirt.  I've only seen one problem with ccloudvm writing to 9p mounts.  I seem to be unable to write to the top level directory in the mount.  So if I mount /home/user I cannot write to /home/user in the guest but I can write to /home/user/src, where src is a directory.

Are you having problems writing to 9p mounts?  There was also a bug that I fixed a while ago which prevented the guest from writing to a 9p mount if the user on the host was not the first user on the host machine.  This has now been fixed.

**Comment by ganeshmaharaj** [comment]
@markdryan duh!! ofcourse you are not using libvirt. *face-palm*. yes, 9p is unable to write to the top level mount but is able to write to the usbdirectories. I don't seem to recall having this problem 2 weeks ago and i have been mounting the same directory the same way.

**Comment by ganeshmaharaj** [comment]
I am going to guess this issue is no longer valid and can be closed. As such, I am doing the same. Feel free to re-open the issue if it is needed.
