### ISSUE TITLE
KVM Permission Denied applies to more than K8s example

### ISSUE THREAD

**Issue by jdandrea** [intel/ccloudvm#88]
Encountering this when trying `ccloudvm create` as a non-root user:

```
$ ccloudvm create --name singlevm --port 8080-80 --debug ciao
Booting VM with 4000 MiB RAM and 2 cpus
To connect to the instance during its creation type

	ssh -q -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i /home/jdandrea/.ccloudvm/id_rsa 127.3.237.2 -p 10022
Error: Failed to launch qemu : exit status 1, Could not access KVM kernel module: Permission denied
failed to initialize KVM: Permission denied
```

Trying `sudo gpasswd -a $USER kvm` did not help.

Consider moving this section:
https://ciao-project.github.io/kubicle.html#failure-to-access-devkvm

... to the main dev (and possibly deploy) instructions for ccloudvm:
https://ciao-project.github.io/developer.html
https://ciao-project.github.io/ciao-deploy.html

**Comment by markdryan** [comment]
This is more of an issue with the ciao documentation rather than with ccloudvm.  The ccloudvm documentation does mention that you may need to run gpasswd and log out and log in again.

https://github.com/intel/ccloudvm#introduction

**Comment by jdandrea** [comment]
Whoops, I missed it. Thank you!
